const el=id=>document.getElementById(id);
const feeMap={Shoes:2500,'Jersey/Bottom':1200,Equipment:0};
const money=n=>'৳'+Math.round(n).toLocaleString('en-US');
const category=()=>document.querySelector('input[name="category"]:checked').value;
function estimate(){const price=Number(el('usdPrice').value),rate=Number(el('fxRate').value),fee=feeMap[category()];const valid=Number.isFinite(price)&&price>0&&Number.isFinite(rate)&&rate>0;return {valid,price,rate,fee,product:price*rate,total:price*rate+fee};}
function update(){const e=estimate();el('productCost').textContent=e.valid?money(e.product):'—';el('feeCost').textContent=e.fee?money(e.fee):'Quoted after review';el('feeUnit').textContent=category()==='Shoes'?'/ pair':category()==='Jersey/Bottom'?'/ item':'';el('totalCost').textContent=!e.valid?'—':e.fee?money(e.total):'Custom quote';el('estimateNote').textContent=!e.valid?'Enter a positive product price and exchange rate to see your estimate.':e.fee?'Estimate only. Final price and payment details confirmed before purchase.':'Product cost shown above. We’ll confirm the equipment service fee separately.';}
function changeCategory(){const c=category();el('sizeLabel').textContent=c==='Shoes'?'Shoe size (US)':c==='Jersey/Bottom'?'Clothing size':'Equipment type';el('size').placeholder=c==='Shoes'?'e.g. Men’s US 10.5':c==='Jersey/Bottom'?'e.g. M / L / XL':'e.g. Goalkeeper gloves';el('size').value='';el('variantLabel').textContent=c==='Jersey/Bottom'?'Team / player / style (optional)':'Color / variant (optional)';const stores=c==='Jersey/Bottom'?['Nike / SNKRS','Adidas','Puma','Under Armour','Fanatics','NBA Store','NFL Shop','Amazon (Sold by Amazon)','Other official / trusted store']:['Nike / SNKRS','Adidas','Puma','Under Armour','New Balance','Foot Locker','Pro Direct US','Finish Line','Amazon (Sold by Amazon)','Other official / trusted store'];el('store').replaceChildren(...stores.map(s=>new Option(s,s)));el('handoff').hidden=true;update();}
document.querySelectorAll('[name="category"]').forEach(r=>r.addEventListener('change',changeCategory));
document.querySelectorAll('[data-category]').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('[name="category"]').forEach(r=>r.checked=r.value===a.dataset.category);changeCategory();}));
el('orderForm').addEventListener('input',()=>{update();el('handoff').hidden=true;});
el('orderForm').addEventListener('submit',event=>{event.preventDefault();const e=estimate();if(!el('orderForm').reportValidity()||!e.valid)return;let link;try{link=new URL(el('productLink').value);if(!['http:','https:'].includes(link.protocol))throw Error();}catch{el('productLink').setCustomValidity('Please enter a valid http or https product link.');el('productLink').reportValidity();return;}const message=['*Sports Solutions Inc. — Order Request*','',`Category: ${category()}`,`Name: ${el('name').value.trim()}`,`Phone: ${el('phone').value.trim()}`,`Store: ${el('store').value}`,`${el('sizeLabel').textContent}: ${el('size').value.trim()}`,`Variant / style: ${el('variant').value.trim()||'—'}`,`Product link: ${link.href}`,`Product price: $${e.price}`,`Estimate rate: ${e.rate} BDT/USD`,`Estimated product cost: ${money(e.product)}`,`Service fee: ${e.fee?money(e.fee):'Please quote'}`,`Estimated total: ${e.fee?money(e.total):'To be confirmed'}`,`Notes: ${el('notes').value.trim()||'—'}`,'','Please confirm availability, final price, payment terms, and delivery window.','I understand delivery is approximately 25 days from the batch ship date.'].join('\n');const url='https://wa.me/14438620065?text='+encodeURIComponent(message);el('retryLink').href=url;el('handoff').hidden=false;window.open(url,'_blank','noopener,noreferrer');});
el('productLink').addEventListener('input',()=>el('productLink').setCustomValidity(''));
el('year').textContent=new Date().getFullYear();update();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_order_estimate',description:'Set category, USD product price, and estimate exchange rate. Updates the calculator only; does not submit an order or open WhatsApp.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['Shoes','Jersey/Bottom','Equipment']},usdPrice:{type:'number',exclusiveMinimum:0},fxRate:{type:'number',exclusiveMinimum:0}},required:['category','usdPrice','fxRate'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Object.hasOwn(feeMap,input.category)||!Number.isFinite(input.usdPrice)||input.usdPrice<=0||!Number.isFinite(input.fxRate)||input.fxRate<=0)throw new Error('Valid category and positive numeric price and rate are required.');document.querySelectorAll('[name="category"]').forEach(r=>r.checked=r.value===input.category);changeCategory();el('usdPrice').value=input.usdPrice;el('fxRate').value=input.fxRate;update();const e=estimate();return {productBDT:e.product,serviceFeeBDT:e.fee||null,totalBDT:e.fee?e.total:null,confirmed:false};}})).catch(()=>{});}catch{}}
